#================================================================================#
# LICENSE (MIT)                                                                  #
#================================================================================#
#                                                                                #
# The MIT License (MIT)                                                          #
#                                                                                #
# Copyright (c) 2026 luau-project https://github.com/luau-project/lnuminfo       #
#                                                                                #
# Permission is hereby granted, free of charge, to any person obtaining a copy   #
# of this software and associated documentation files (the "Software"), to deal  #
# in the Software without restriction, including without limitation the rights   #
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      #
# copies of the Software, and to permit persons to whom the Software is          #
# furnished to do so, subject to the following conditions:                       #
#                                                                                #
# The above copyright notice and this permission notice shall be included in all #
# copies or substantial portions of the Software.                                #
#                                                                                #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    #
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  #
# SOFTWARE.                                                                      #
#                                                                                #
#================================================================================#

__EMPTY =
DIRSEP = /
OBJEXT = .o
LIBEXT = .so
OPENARGDELIMITER = "
CLOSEARGDELIMITER = $(OPENARGDELIMITER)

PACKAGE_NAME = lnuminfo
PACKAGE_VERSION = 0.0.1
PACKAGE_REVISION = 1
PACKAGE_REPOSITORY_URL = https://github.com/luau-project/$(PACKAGE_NAME)
PACKAGE_SOURCE_URL = git+$(PACKAGE_REPOSITORY_URL).git
PACKAGE_SOURCE_BRANCH = main
PACKAGE_TAG = v$(PACKAGE_VERSION)
PACKAGE_HOMEPAGE_URL = $(PACKAGE_REPOSITORY_URL)
ROCKSPEC_EXT = .rockspec
ROCKSPEC_DIR = rockspecs
ROCKSPEC_TEMPLATE = $(ROCKSPEC_DIR)$(DIRSEP)rockspec.in
DEV_ROCKSPEC_VERSION = dev
DEV_ROCKSPEC_REVISION = 1
DEV_ROCKSPEC = $(ROCKSPEC_DIR)$(DIRSEP)$(PACKAGE_NAME)-$(DEV_ROCKSPEC_VERSION)-$(DEV_ROCKSPEC_REVISION)$(ROCKSPEC_EXT)
VERSIONED_ROCKSPEC = $(ROCKSPEC_DIR)$(DIRSEP)$(PACKAGE_NAME)-$(PACKAGE_VERSION)-$(PACKAGE_REVISION)$(ROCKSPEC_EXT)

CC = cc
CCONLY = -c
CCPIC = -fPIC
CCSTD = -std=gnu99
CCOPT = -O2
CCWARN = -Wall -Wextra
CFLAGS = $(CCSTD) $(CCPIC) $(CCOPT) $(CCWARN)
CCOUT = -o $(__EMPTY)
CCDEFFLAG = -D
CCINCFLAG = -I

LD = $(CC)
LDSHARED = -shared
LDFLAGS = $(LDSHARED)
LDOUT = $(CCOUT)

PREFIX = $(DIRSEP)usr$(DIRSEP)local
LUA = lua
LUA_VERSION = 5.1
LUA_INCDIR = $(PREFIX)$(DIRSEP)include
INSTALL_LMOD = $(PREFIX)$(DIRSEP)share$(DIRSEP)lua$(DIRSEP)$(LUA_VERSION)

TNUMINFO_NAME = tnuminfo
TNUMINFO_SRC = $(TNUMINFO_NAME).c
TNUMINFO_OBJ = $(TNUMINFO_NAME)$(OBJEXT)
TNUMINFO_LIB = $(TNUMINFO_NAME)$(LIBEXT)

LUAROCKS = luarocks
LUAROCKSLINTARGS =
LUAROCKSMAKEARGS =

TESTDRIVER = test.lua
TESTCOVFLAG = --coverage

COVRUNNER = luacov
COVSTAT = luacov.stats.out
COVREPORT = luacov.report.out
COVIEEE754BINARY64 = IEEE-754-binary64
COVIEEE754BINARY32 = IEEE-754-binary32
COVIEEE754BINARY64EXTENDED = IEEE-754-binary64-extended

ADDTOSTDOUT = >>
TOSTDOUT = >

ENV = env
QUESTIONMARK = ?
SEMICOLON = ;
LUA_CPATH_THIS_DIR = .$(DIRSEP)$(QUESTIONMARK)$(LIBEXT)$(SEMICOLON)$(SEMICOLON)

SED = sed
SEDEFLAG = -e

ECHO = echo
ECHOOPENDELIMITER = "
ECHOCLOSEDELIMITER = $(ECHOOPENDELIMITER)
ECHOESCAPEDELIMITER = \$(ECHOOPENDELIMITER)
ECHOEMPTY = $(ECHO) $(ECHOOPENDELIMITER)$(ECHOCLOSEDELIMITER)

RM = rm
RMFLAG = -f

MKDIR = mkdir
MKDIRFLAG = -p

INSTALL = install
INSTALLFLAG = -m 0644

all: create-rockspecs

create-install-dir:
	-$(MKDIR) $(MKDIRFLAG) $(OPENARGDELIMITER)$(INSTALL_LMOD)$(CLOSEARGDELIMITER)

install: $(PACKAGE_NAME).lua create-install-dir
	$(INSTALL) $(INSTALLFLAG) $(PACKAGE_NAME).lua $(OPENARGDELIMITER)$(INSTALL_LMOD)$(CLOSEARGDELIMITER)

uninstall:
	-$(RM) $(RMFLAG) $(OPENARGDELIMITER)$(INSTALL_LMOD)$(DIRSEP)$(PACKAGE_NAME).lua$(CLOSEARGDELIMITER)

coverage: $(COVREPORT)

$(COVREPORT): $(COVSTAT)
	$(COVRUNNER)

test: $(TESTDRIVER)
	$(ENV) $(OPENARGDELIMITER)LUA_CPATH=$(LUA_CPATH_THIS_DIR)$(CLOSEARGDELIMITER) $(LUA) $(TESTDRIVER)

test-with-cov: $(TESTDRIVER)
	$(ENV) $(OPENARGDELIMITER)LUA_CPATH=$(LUA_CPATH_THIS_DIR)$(CLOSEARGDELIMITER) $(LUA) $(TESTDRIVER) $(TESTCOVFLAG)

c-test: tnuminfo-lib test

c-test-with-cov: tnuminfo-lib test-with-cov

luarocks-install-dev: $(DEV_ROCKSPEC)
	$(LUAROCKS) make $(LUAROCKSMAKEARGS) $(DEV_ROCKSPEC)

luarocks-install: $(VERSIONED_ROCKSPEC)
	$(LUAROCKS) make $(LUAROCKSMAKEARGS) $(VERSIONED_ROCKSPEC)

luarocks-uninstall-dev:
	$(LUAROCKS) remove $(LUAROCKSREMOVEARGS) $(DEV_ROCKSPEC)

luarocks-uninstall:
	$(LUAROCKS) remove $(LUAROCKSREMOVEARGS) $(VERSIONED_ROCKSPEC)

lint-rockspecs: lint-dev-rockspec lint-rockspec

lint-dev-rockspec: $(DEV_ROCKSPEC)
	$(LUAROCKS) lint $(LUAROCKSLINTARGS) $(DEV_ROCKSPEC)

lint-rockspec: $(VERSIONED_ROCKSPEC)
	$(LUAROCKS) lint $(LUAROCKSLINTARGS) $(VERSIONED_ROCKSPEC)

create-rockspecs: create-dev-rockspec create-rockspec

create-dev-rockspec: $(DEV_ROCKSPEC)

create-rockspec: $(VERSIONED_ROCKSPEC)

$(DEV_ROCKSPEC): $(ROCKSPEC_TEMPLATE)
	$(SED) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_NAME@|$(PACKAGE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_VERSION@|$(DEV_ROCKSPEC_VERSION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REVISION@|$(DEV_ROCKSPEC_REVISION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REPOSITORY_URL@|$(PACKAGE_REPOSITORY_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_URL@|$(PACKAGE_SOURCE_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_BRANCH@|$(PACKAGE_SOURCE_BRANCH)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_TAG@|$(PACKAGE_TAG)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_HOMEPAGE_URL@|$(PACKAGE_HOMEPAGE_URL)|g$(CLOSEARGDELIMITER) $(ROCKSPEC_TEMPLATE)$(TOSTDOUT) $(DEV_ROCKSPEC)

$(VERSIONED_ROCKSPEC): $(ROCKSPEC_TEMPLATE)
	$(SED) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_NAME@|$(PACKAGE_NAME)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_VERSION@|$(PACKAGE_VERSION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REVISION@|$(PACKAGE_REVISION)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_REPOSITORY_URL@|$(PACKAGE_REPOSITORY_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_URL@|$(PACKAGE_SOURCE_URL)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_SOURCE_BRANCH@|$(PACKAGE_SOURCE_BRANCH)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_TAG@|$(PACKAGE_TAG)|g$(CLOSEARGDELIMITER) $(SEDEFLAG) $(OPENARGDELIMITER)s|@PACKAGE_HOMEPAGE_URL@|$(PACKAGE_HOMEPAGE_URL)|g$(CLOSEARGDELIMITER) $(ROCKSPEC_TEMPLATE)$(TOSTDOUT) $(VERSIONED_ROCKSPEC)

tnuminfo-lib: $(TNUMINFO_LIB)

$(TNUMINFO_LIB): $(TNUMINFO_OBJ)
	$(LD) $(LDFLAGS) $(LDOUT)$(TNUMINFO_LIB) $(TNUMINFO_OBJ)

$(TNUMINFO_OBJ): $(TNUMINFO_SRC)
	$(CC) $(CCONLY) $(CFLAGS) $(CCINCFLAG) $(OPENARGDELIMITER)$(LUA_INCDIR)$(CLOSEARGDELIMITER) $(CCOUT)$(TNUMINFO_OBJ) $(TNUMINFO_SRC)

clean-tnuminfo-obj:
	-$(RM) $(RMFLAG) $(TNUMINFO_OBJ)

clean-tnuminfo-lib:
	-$(RM) $(RMFLAG) $(TNUMINFO_LIB)

clean-tnuminfo: clean-tnuminfo-obj clean-tnuminfo-lib

clean-cov-stat:
	-$(RM) $(RMFLAG) $(COVSTAT)

clean-cov-report:
	-$(RM) $(RMFLAG) $(COVREPORT)

clean-cov: clean-cov-stat clean-cov-report

clean-dev-rockspec:
	-$(RM) $(RMFLAG) $(DEV_ROCKSPEC)

clean-rockspec:
	-$(RM) $(RMFLAG) $(VERSIONED_ROCKSPEC)

clean: clean-tnuminfo clean-cov clean-dev-rockspec clean-rockspec
