name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

permissions:
  contents: read

env:
  # datafile
  DATAFILE_VERSION: 0.11
  DATAFILE_ROCKSPEC_REV: 1

  # luacov
  LUACOV_VERSION: 0.17.0
  LUACOV_ROCKSPEC_REV: 1

  # cluacov
  CLUACOV_VERSION: 1.0.0
  CLUACOV_ROCKSPEC_REV: 1

jobs:
  test-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - ubuntu-24.04-arm
          - windows-11-arm

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        toolchain:
          - msvc
          - cc

        exclude:

          - os: ubuntu-latest
            toolchain: msvc

          - os: macos-latest
            toolchain: msvc

          - os: windows-11-arm
            toolchain: cc

          - os: ubuntu-24.04-arm
            toolchain: msvc
    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup MSVC developer prompt
        uses: step-security/msvc-dev-cmd@22c98154b708dbd743e6f27a933cf6ceba3305c4 # v1.13.1
        if: ${{ runner.os == 'Windows' && matrix.toolchain == 'msvc' }}
        with:
          arch: ${{ runner.arch }}

      - name: Install Lua
        uses: luau-project/setup-lua@c47c002fc60841a11b22ef3058c86a3d08acf218 # v2.0.1
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Print Lua version
        run: lua -v

      - name: Print LuaRocks version
        run: luarocks --version

      - name: Restore datafile tarball
        id: restore-datafile-tarball
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz
          key: datafile-${{ env.DATAFILE_VERSION }}
          enableCrossOsArchive: true

      - name: Download datafile
        if: ${{ steps.restore-datafile-tarball.outputs.cache-hit != 'true' }}
        run: curl -L --create-dirs -o "deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz" "https://github.com/hishamhm/datafile/archive/refs/tags/v${{ env.DATAFILE_VERSION }}.tar.gz"

      - name: Save datafile tarball
        if: ${{ steps.restore-datafile-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz
          key: datafile-${{ env.DATAFILE_VERSION }}
          enableCrossOsArchive: true

      - name: Extract datafile
        run: tar -xf "deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz"

      - name: Install datafile
        working-directory: datafile-${{ env.DATAFILE_VERSION }}
        run: luarocks make "rockspecs/datafile-${{ env.DATAFILE_VERSION }}-${{ env.DATAFILE_ROCKSPEC_REV }}.rockspec"

      - name: Restore luacov tarball
        id: restore-luacov-tarball
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz
          key: luacov-${{ env.LUACOV_VERSION }}
          enableCrossOsArchive: true

      - name: Download luacov
        if: ${{ steps.restore-luacov-tarball.outputs.cache-hit != 'true' }}
        run: curl -L --create-dirs -o "deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz" "https://github.com/lunarmodules/luacov/archive/refs/tags/v${{ env.LUACOV_VERSION }}.tar.gz"

      - name: Save luacov tarball
        if: ${{ steps.restore-luacov-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz
          key: luacov-${{ env.LUACOV_VERSION }}
          enableCrossOsArchive: true

      - name: Extract luacov
        run: tar -xf "deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz"

      - name: Install luacov
        working-directory: luacov-${{ env.LUACOV_VERSION }}
        run: luarocks make "rockspecs/luacov-${{ env.LUACOV_VERSION }}-${{ env.LUACOV_ROCKSPEC_REV }}.rockspec"

      - name: Restore cluacov tarball
        id: restore-cluacov-tarball
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz
          key: cluacov-${{ env.CLUACOV_VERSION }}
          enableCrossOsArchive: true

      - name: Download cluacov
        if: ${{ steps.restore-cluacov-tarball.outputs.cache-hit != 'true' }}
        run: curl -L --create-dirs -o "deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz" "https://github.com/lunarmodules/cluacov/archive/refs/tags/${{ env.CLUACOV_VERSION }}.tar.gz"

      - name: Save cluacov tarball
        if: ${{ steps.restore-cluacov-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz
          key: cluacov-${{ env.CLUACOV_VERSION }}
          enableCrossOsArchive: true

      - name: Extract cluacov
        run: tar -xf "deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz"

      - name: Install cluacov
        working-directory: cluacov-${{ env.CLUACOV_VERSION }}
        run: luarocks make "rockspecs/cluacov-${{ env.CLUACOV_VERSION }}-${{ env.CLUACOV_ROCKSPEC_REV }}.rockspec"

      - name: Lint rockspec, Test with Coverage and Generate Coverage Report (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        run: |
          IF "${{ matrix.toolchain }}" EQU "msvc" (
            SET "CURRENT_MAKE=nmake"
            SET "CURRENT_MAKE_FILE_FLAG=/F"
          ) ELSE IF "${{ matrix.toolchain }}" EQU "cc" (
            SET "CURRENT_MAKE=mingw32-make"
            SET "CURRENT_MAKE_FILE_FLAG=-f"
          ) ELSE (
            ECHO Unexpected matrix.toolchain: ${{ matrix.toolchain }}
            EXIT /B 1
          )

          FOR /F "TOKENS=* USEBACKQ" %%D IN (`luarocks config variables.LUA_DIR`) ^
          DO FOR /F "TOKENS=* USEBACKQ" %%I IN (`luarocks config variables.LUA_INCDIR`) ^
          DO FOR /F "TOKENS=* USEBACKQ" %%A IN (`luarocks config variables.LUA_LIBDIR`) ^
          DO FOR /F "TOKENS=* USEBACKQ" %%B IN (`luarocks config variables.LUALIB`) ^
          DO %CURRENT_MAKE% %CURRENT_MAKE_FILE_FLAG% Makefile.windows "PREFIX=%%D" "LUA_INCDIR=%%I" "LUA_CPATH=%LUA_CPATH%" "LUA_IMPLIB=%%A\%%B" clean all lint-rockspecs c-test-with-cov coverage

      - name: Lint rockspec, Test with Coverage and Generate Coverage Report (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            make \
              -f Makefile.unix \
              "PREFIX=$(luarocks config variables.LUA_DIR)" \
              "LUA_INCDIR=$(luarocks config variables.LUA_INCDIR)" \
              "LUA_CPATH=$LUA_CPATH" \
              clean all lint-rockspecs c-test-with-cov coverage
          elif [ "${{ runner.os }}" = "macOS" ]; then
            make \
              -f Makefile.unix \
              "LDSHARED=-bundle -undefined dynamic_lookup -all_load" \
              "PREFIX=$(luarocks config variables.LUA_DIR)" \
              "LUA_INCDIR=$(luarocks config variables.LUA_INCDIR)" \
              "LUA_CPATH=$LUA_CPATH" \
              clean all lint-rockspecs c-test-with-cov coverage
          else
            echo "Unexpected runner.os: ${{ runner.os }}";
            exit 1;
          fi

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
