name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

permissions:
  contents: read

env:
  # datafile
  DATAFILE_VERSION: 0.11
  DATAFILE_ROCKSPEC_REV: 1

  # luacov
  LUACOV_VERSION: 0.17.0
  LUACOV_ROCKSPEC_REV: 1

  # cluacov
  CLUACOV_VERSION: 1.0.0
  CLUACOV_ROCKSPEC_REV: 1

jobs:
  test-IEEE-754-binary64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

        lua-version:
          - 5.1
          - 5.2
          - 5.3
          - 5.4
          - 5.5
          - luajit
          - openresty

        toolchain:
          - msvc
          - cc

        exclude:

          - os: ubuntu-latest
            toolchain: msvc

          - os: macos-latest
            toolchain: msvc
    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup MSVC developer prompt
        uses: step-security/msvc-dev-cmd@22c98154b708dbd743e6f27a933cf6ceba3305c4 # v1.13.1
        if: ${{ runner.os == 'Windows' && matrix.toolchain == 'msvc' }}

      - name: Install Lua
        uses: luau-project/setup-lua@c47c002fc60841a11b22ef3058c86a3d08acf218 # v2.0.1
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Print Lua version
        run: lua -v

      - name: Print LuaRocks version
        run: luarocks --version

      - name: Restore datafile tarball
        id: restore-datafile-tarball
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz
          key: datafile
          enableCrossOsArchive: true

      - name: Download datafile
        if: ${{ steps.restore-datafile-tarball.outputs.cache-hit != 'true' }}
        run: curl -L --create-dirs -o "deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz" "https://github.com/hishamhm/datafile/archive/refs/tags/v${{ env.DATAFILE_VERSION }}.tar.gz"

      - name: Save datafile tarball
        if: ${{ steps.restore-datafile-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz
          key: datafile
          enableCrossOsArchive: true

      - name: Extract datafile
        run: tar -xf "deps/datafile-${{ env.DATAFILE_VERSION }}.tar.gz"

      - name: Install datafile
        working-directory: datafile-${{ env.DATAFILE_VERSION }}
        run: luarocks make "rockspecs/datafile-${{ env.DATAFILE_VERSION }}-${{ env.DATAFILE_ROCKSPEC_REV }}.rockspec"

      - name: Restore luacov tarball
        id: restore-luacov-tarball
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz
          key: luacov
          enableCrossOsArchive: true

      - name: Download luacov
        if: ${{ steps.restore-luacov-tarball.outputs.cache-hit != 'true' }}
        run: curl -L --create-dirs -o "deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz" "https://github.com/lunarmodules/luacov/archive/refs/tags/v${{ env.LUACOV_VERSION }}.tar.gz"

      - name: Save luacov tarball
        if: ${{ steps.restore-luacov-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz
          key: luacov
          enableCrossOsArchive: true

      - name: Extract luacov
        run: tar -xf "deps/luacov-${{ env.LUACOV_VERSION }}.tar.gz"

      - name: Install luacov
        working-directory: luacov-${{ env.LUACOV_VERSION }}
        run: luarocks make "rockspecs/luacov-${{ env.LUACOV_VERSION }}-${{ env.LUACOV_ROCKSPEC_REV }}.rockspec"

      - name: Restore cluacov tarball
        id: restore-cluacov-tarball
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz
          key: cluacov
          enableCrossOsArchive: true

      - name: Download cluacov
        if: ${{ steps.restore-cluacov-tarball.outputs.cache-hit != 'true' }}
        run: curl -L --create-dirs -o "deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz" "https://github.com/lunarmodules/cluacov/archive/refs/tags/${{ env.CLUACOV_VERSION }}.tar.gz"

      - name: Save cluacov tarball
        if: ${{ steps.restore-cluacov-tarball.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz
          key: cluacov
          enableCrossOsArchive: true

      - name: Extract cluacov
        run: tar -xf "deps/cluacov-${{ env.CLUACOV_VERSION }}.tar.gz"

      - name: Install cluacov
        working-directory: cluacov-${{ env.CLUACOV_VERSION }}
        run: luarocks make "rockspecs/cluacov-${{ env.CLUACOV_VERSION }}-${{ env.CLUACOV_ROCKSPEC_REV }}.rockspec"

      - name: Lint rockspec, Test with Coverage and Generate Coverage Report through NMake
        if: ${{ runner.os == 'Windows' && matrix.toolchain == 'msvc' }}
        run: nmake /F Makefile.windows clean all lint-rockspecs test-ieee-754-binary64-with-cov coverage

      - name: Lint rockspec, Test with Coverage and Generate Coverage Report through GNU Make for MinGW / MinGW-w64
        if: ${{ runner.os == 'Windows' && matrix.toolchain != 'msvc' }}
        run: mingw32-make -f Makefile.windows clean all lint-rockspecs test-ieee-754-binary64-with-cov coverage

      - name: Lint rockspec, Test with Coverage and Generate Coverage Report through make
        if: ${{ runner.os != 'Windows' }}
        run: make -f Makefile.unix clean all lint-rockspecs test-ieee-754-binary64-with-cov coverage

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}